### ISSUE TITLE
FIX : Corrección de Error en la Línea 118 del Archivo colores.html

### ISSUE THREAD

**Issue by jhojax12866** [meroh1/inventario_tienda_labuela#40]
## Descripción
En la línea 118 del archivo colores.html arroja un error "Uncaught TypeError: Cannot set properties of null (setting 'textContent')".

## Pasos para Reproducir
-Abre el archivo colores.html en un navegador web.
-Interactúa con la página según sea necesario para llegar al punto donde se produce el error.
-Observa el error "Uncaught TypeError: Cannot set properties of null (setting 'textContent')" en la consola del navegador.

## Comportamiento Esperado
en la línea 118 del archivo colores.html no debería arrojar ningún error y debería funcionar correctamente para mostrar el nombre del usuario.

## Capturas de Pantalla (si es relevante)
[Agrega capturas de pantalla que ayuden a comprender el problema o la tarea.]

## Información Adicional (si es relevante)
El error se produce al intentar establecer el textContent de un elemento identificado por su id en la línea 118 del archivo colores.html.
Este error afecta la funcionalidad de mostrar el nombre del usuario en la página.

**Comment by meroh1** [comment]
melo
